--- #YAML:1.0
name:               Object-Wrapper
version:            0.04
abstract:           Sanity-check wrapper for objects.
author:
    - Steven Lembark <lembark@wrkhors.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    parent:        0.2
    Scalar::Util:  0
    strict:        0
    Symbol:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
